config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories do
    resources :products do
      resources :reviews
    end
  end
  resources :products, only: [:index]
  root 'categories#index'
  #get '/categories/:category_id/products', to: 'products#index'
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  validates :name, presence: true, uniqueness: { case_sensitive: true }
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :reviews

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true, :format => { :with => /\A(\$)?(\d+)(\.|,)?\d{0,2}?\z/}


  def average_rating
	if self.reviews.size > 0
    	self.reviews.average(:rating).round(2)
    else
        'no ratings'
    end
  end

  
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
  has_many :products
  validates :firstname, presence: true
  validates :lastname, presence: true

  def admin?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  protect_from_forgery with: :exception

    protected

  def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:firstname, :lastname, :email, :password, :password_confirmation, :remember_me) }
     devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:firstname, :username, :email, :password, :remember_me) }
     devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:firstname, :lastname, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :create]
  before_action :require_admin, only: [:new, :edit, :update, :destroy, :create]
  
  expose(:categories)
  expose(:category)
  expose(:product) { Product.new }

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    self.category = Category.new(category_params)

    if category.save
      redirect_to category, notice: 'Category was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if category.update(category_params)
      redirect_to category, notice: 'Category was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end

    def require_admin
      unless current_user.admin?
        redirect_to new_user_session_path, :flash => {error: "You must be admin to access this section."}
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_filter :authenticate_user!, :except => [:index, :show]
before_action :authorize_user, :only => [:edit, :update, :destroy]
  expose(:category)
  expose(:products)
  expose(:product) 
  expose(:review) { Review.new }
  expose_decorated(:reviews, ancestor: :product)

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    self.product = Product.new(product_params)
    if product.save
      category.products << product
      current_user.products << product
      redirect_to category_product_url(category, product), notice: 'Product was successfully created.'
    else
      render action: 'new'
    end
  end
  def update
    if product.update(product_params)
      redirect_to category_product_url(category, product), notice: 'Product was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /products/1
  def destroy
    product.destroy
    redirect_to category_url(category), notice: 'Product was successfully destroyed.'
  end

  private
    def product_params
      params.require(:product).permit(:title, :description, :price, :category_id)
    end
    def authorize_user
      if product.user != current_user
         redirect_to category_product_url(category, product), :flash => {error: "You are not allowed to edit this product."}
      end
      
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  expose(:review)
  expose(:product)

  def edit
  end

  def create
    self.review = Review.new(review_params)

    if review.save
      product.reviews << review
      current_user.reviews << review
      redirect_to category_product_url(product.category, product), notice: 'Review was successfully created.'
    else
      render action: 'new'
    end
  end

  def destroy
    review.destroy
    redirect_to category_product_url(product.category, product), notice: 'Review was successfully destroyed.'
  end

  private
    def review_params
      params.require(:review).permit(:content, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def price_format(product)
	number_to_currency(product.price, precision: 2)
  end
  
end

app/views/categories/_form.html.haml
= simple_form_for([category], :html => {:class => 'form-horizontal' }, wrapper: :horizontal_form) do |f|
  = f.error_notification
  = f.input :name
  .pull-right= f.button :submit

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Listing categories
%table.table-striped.table-hover.table
  %tr
    %th Name
    %th
    %th
    %th

  - categories.each do |category|
    %tr
      %td= category.name
      %td= link_to 'Show', category
      %td= link_to 'Edit', edit_category_path(category)
      %td= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Category', new_category_path, class:"btn btn-primary btn-large"

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%h2
  %b Name:
  = category.name

%ul.list-unstyled
  -category.products.each do | product |
    %li
      =link_to product.title, category_product_path(category, product)
      =price_format(product)
      %p=product.description.truncate(80)

%p
  %h3 New product
  = render 'products/form'

= link_to 'Edit', edit_category_path(category)
\|
= link_to 'Back', categories_path

app/views/layouts/_alert.haml
- flash.each do |name, msg|
  %div{class: "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
    %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} &times;
    = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_header.haml
%nav.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Machine that goes ping', root_path, class: "navbar-brand"
    #navbar-collapse.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li= link_to 'Categories', categories_url
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in? == false
          %li= link_to 'Login', new_user_session_path
          %li= link_to 'Sign Up', new_user_registration_path
        - else
          %li= link_to current_user.email, edit_user_registration_path
          %li= link_to 'Log Out', destroy_user_session_path, :method => :delete
       

app/views/layouts/application.haml
!!!
%html{ lang: 'en' }
  %head
    %meta{ charset: 'utf-8' }/
    %meta{ content: 'IE=Edge,chrome=1', 'http-equiv' => 'X-UA-Compatible' }/
    %meta{ content: 'width=device-width, initial-scale=1.0', name: 'viewport' }/
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

  %body
    = render 'layouts/header'
    .container-fluid
      .col-md-6.col-md-offset-3
        = render "layouts/alert"
        = yield

app/views/products/_form.html.haml
= simple_form_for([category,product], :html => {:class => 'form-horizontal' }, wrapper: :horizontal_form) do |f|
  = f.error_notification
  = f.input :title
  = f.input :description
  = f.input :price
  .pull-right= f.button :submit

app/views/products/edit.html.haml
%h1 Editing product
= render 'form'

= link_to 'Show', category_product_path(category, product)
\|
= link_to 'Back', category_path(category)

app/views/products/index.html.haml
%h1 Listing products

%table.table-striped.table-hover.table
  %tr
    %th Title
    %th Description
    %th Price
    %th
    %th
    %th

  - products.each do |product|
    %tr
      %td= product.title
      %td= product.description
      %td= price_format(product)
      %td= link_to 'Show', category_product_path(product.category, product)
      %td= link_to 'Edit', edit_category_product_path(product.category, product)
      %td= link_to 'Destroy', category_product_path(product.category, product), method: :delete, data: { confirm: 'Are you sure?' }

%br

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', category_products_path

app/views/products/show.html.haml
%h3
  %b Title:
  = product.title
%p
  %b Description:
  = product.description
%p
  %b Price:
  = price_format(product)
%p
  %b Category:
  = link_to product.category.name, category_path(category)
%p
  %b Rating:
  = product.average_rating


.container-fluid
  .col-md-9.col-md-offset-3
    = render 'reviews/form'
%p

= render 'reviews/review'

= link_to 'Edit', edit_category_product_path(category.id, product.id)
\|
= link_to 'Back', category_products_path

app/views/reviews/_form.html.haml
= simple_form_for([category,product, review], :html => {:class => 'form-horizontal' }, wrapper: :horizontal_form) do |f|
  = f.error_notification
  = f.input :content
  = f.input :rating, collection: 1..5
  .pull-right= f.button :submit

app/views/reviews/_review.html.haml
.panel.panel-default
  .panel-heading #{reviews.size} Reviews
  %ul.list-group
  - reviews.each do |review|
    %li.list-group-item
      = review.author
      %span.badge= review.rating
      %p= review.content